### ISSUE TITLE
error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' 

### ISSUE THREAD

**Issue by richardor** [bincrafters/conan-protobuf#3]
when i use the binary: protobuf/3.5.1@bincrafters/stable, the error occurs like this :
error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug'   ... libprotobuf-lited.lib..

**Comment by jgsogo** [comment]
(Just for reference, although it was my fault, I pointed you here: https://github.com/bincrafters/community/issues/77#issuecomment-359513713)

You are compiling protobuf with `static_rt=True` (it is the default option), while your project is being compiled using dynamic. Check [here](https://github.com/bincrafters/conan-protobuf/blob/testing/3.5.1/test_package/CMakeLists.txt#L12) how to handle static/dynamic flag.

**Comment by solvingj** [comment]
closing before disabling project-level issues.  please continue discussion in ticket below if necessary: 
https://github.com/bincrafters/community/issues/77#issuecomment-359513713
